# Generated by Django 4.2.30 on 2026-08-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_section_responsable_n1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Généré automatiquement : REC + AAMMM + séquence (ex : REC2511001)', max_length=30, unique=True, verbose_name='Référence')),
                ('numero_interne', models.CharField(blank=True, max_length=50, verbose_name='N° Interne')),
                ('numero_reclamation_client', models.CharField(blank=True, max_length=100, verbose_name='N° Réclamation Client')),
                ('type_signalement', models.CharField(choices=[('R', 'Réclamation Qualité (Formelle - 8D)'), ('I', 'Incident Client (Informel - Doc 05)'), ('AI', 'Amélioration Interne (Doc 05)')], default='R', max_length=5, verbose_name='Type de signalement')),
                ('mode_traitement', models.CharField(choices=[('8D', 'Rapport 8D (Doc 83)'), ('DOC05', "Fiche d'incident simplifiée (Doc 05)")], default='8D', max_length=10, verbose_name='Support de traitement')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('d1_d3', 'D1-D3 : Prise en charge & Sécurisation'), ('d4_d6', "D4-D6 : Analyse & Plan d'actions"), ('d7_d8', 'D7-D8 : Capitalisation & Clôture'), ('cloture', 'Clôturé')], default='d1_d3', max_length=20, verbose_name='Statut du dossier')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Client')),
                ('contact_client', models.CharField(blank=True, max_length=200, verbose_name='Contact client')),
                ('description_piece', models.CharField(blank=True, max_length=255, verbose_name='Description pièce / prestation')),
                ('reference_piece', models.CharField(blank=True, max_length=100, verbose_name='Référence pièce')),
                ('quantite_impactee', models.PositiveIntegerField(default=0, verbose_name='Quantité impactée')),
                ('est_probleme_repetitif', models.BooleanField(default=False, verbose_name='Problème répétitif ?')),
                ('date_alerte_client', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'alerte client")),
                ('date_ouverture', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ouverture fiche")),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='Date de mise à jour')),
                ('date_incident', models.DateField(blank=True, null=True, verbose_name="Date de l'incident")),
                ('date_envoi_d1_d3', models.DateField(blank=True, null=True, verbose_name='Date envoi D1-D3 au client')),
                ('accuse_reception_envoye', models.BooleanField(default=False, verbose_name='Accusé de réception écrit envoyé au client')),
                ('date_accuse_reception', models.DateField(blank=True, null=True, verbose_name="Date d'accusé de réception")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_clients', to='accounts.section', verbose_name='Section')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_clients', to='accounts.site', verbose_name='Site concerné')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations_clients', to='accounts.societe', verbose_name='Société')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Réclamation Client',
                'verbose_name_plural': 'Réclamations Clients',
                'ordering': ['-date_alerte_client', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Participant8D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_externe', models.CharField(blank=True, max_length=200, verbose_name='Nom externe')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction')),
                ('est_pilote', models.BooleanField(default=False, verbose_name='Pilote de la réclamation')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations_8d', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur interne')),
            ],
            options={
                'verbose_name': 'Participant 8D',
                'verbose_name_plural': 'Participants 8D',
            },
        ),
        migrations.CreateModel(
            name='MesureConservatoireD3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mesure', models.CharField(choices=[('tri_interne', 'Tri stock interne'), ('tri_externe', 'Tri stock externe'), ('repere_unitaire', 'Repère unitaire'), ('autre', 'Autre action')], max_length=30, verbose_name='Type de mesure')),
                ('selectionne', models.BooleanField(default=False, verbose_name='Appliquée ?')),
                ('quantite_triee', models.PositiveIntegerField(default=0, verbose_name='Quantité triée')),
                ('quantite_nok', models.PositiveIntegerField(default=0, verbose_name='Quantité NOK')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_conservatoires', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Mesure conservatoire D3',
                'verbose_name_plural': 'Mesures conservatoires D3',
            },
        ),
        migrations.CreateModel(
            name='DescriptionQQOQCCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_client', models.TextField(blank=True, verbose_name='Description du problème par le client')),
                ('quoi_est', models.TextField(blank=True, verbose_name='QUOI (Objet / Défaillance) - EST')),
                ('quoi_nest_pas', models.TextField(blank=True, verbose_name="QUOI - N'EST PAS")),
                ('qui_est', models.TextField(blank=True, verbose_name='QUI (Rencontre le problème) - EST')),
                ('qui_nest_pas', models.TextField(blank=True, verbose_name="QUI - N'EST PAS")),
                ('ou_est', models.TextField(blank=True, verbose_name='OÙ (Secteur / Site) - EST')),
                ('ou_nest_pas', models.TextField(blank=True, verbose_name="OÙ - N'EST PAS")),
                ('quand_est', models.TextField(blank=True, verbose_name='QUAND (Détecté quand / par qui) - EST')),
                ('quand_nest_pas', models.TextField(blank=True, verbose_name="QUAND - N'EST PAS")),
                ('comment_est', models.TextField(blank=True, verbose_name='COMMENT (Se manifeste le problème) - EST')),
                ('comment_nest_pas', models.TextField(blank=True, verbose_name="COMMENT - N'EST PAS")),
                ('combien_est', models.TextField(blank=True, verbose_name='COMBIEN (Combien de pièces) - EST')),
                ('combien_nest_pas', models.TextField(blank=True, verbose_name="COMBIEN - N'EST PAS")),
                ('pourquoi_est', models.TextField(blank=True, verbose_name='POURQUOI (Est-ce un problème) - EST')),
                ('pourquoi_nest_pas', models.TextField(blank=True, verbose_name="POURQUOI - N'EST PAS")),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qqoqccp', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Description QQOQCCP D2',
                'verbose_name_plural': 'Descriptions QQOQCCP D2',
            },
        ),
        migrations.CreateModel(
            name='ClotureRecevabiliteD8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_recevabilite', models.CharField(choices=[('recevable', 'Recevable (Responsabilité AB Serve avérée)'), ('non_recevable', 'Non Recevable (Refus justifié)'), ('partiel', 'Partiellement Recevable')], default='recevable', max_length=20, verbose_name='Recevabilité')),
                ('motif_decision_factuel', models.TextField(blank=True, verbose_name='Motif de la décision (Justification factuelle obligatoire en cas de refus)')),
                ('feliciter_equipe', models.BooleanField(default=False, verbose_name="Féliciter l'équipe ?")),
                ('date_felicitations', models.DateField(blank=True, null=True, verbose_name='Date félicitations')),
                ('date_envoi_8d_final', models.DateField(blank=True, null=True, verbose_name="Date d'envoi du 8D final au client")),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloture_d8', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Clôture & Recevabilité D8',
                'verbose_name_plural': 'Clôtures & Recevabilités D8',
            },
        ),
        migrations.CreateModel(
            name='CapitalisationSMQSD7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc01_instruction', models.BooleanField(default=False, verbose_name='Doc.01 Instruction de travail')),
                ('doc01_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('doc5_24_competences', models.BooleanField(default=False, verbose_name='Doc 5-24 Tableau de compétences')),
                ('doc5_24_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('doc21_formation', models.BooleanField(default=False, verbose_name='Doc.21 Formation nouvel arrivant')),
                ('doc21_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('doc34_habilitation_indiv', models.BooleanField(default=False, verbose_name='Doc 34 Habilitation individuelle')),
                ('doc34_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('doc38_habilitation_poste', models.BooleanField(default=False, verbose_name='Doc 38 Habilitation au poste')),
                ('doc38_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('doc12_gammes', models.BooleanField(default=False, verbose_name='Doc 12 Gamme de travail')),
                ('doc12_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('precisez_gammes', models.TextField(blank=True, verbose_name='Précisez les Gammes')),
                ('doc50_ok_demarrage', models.BooleanField(default=False, verbose_name='Doc 50 OK démarrage')),
                ('doc50_pilote_delai', models.CharField(blank=True, max_length=150)),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capitalisation_d7', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Capitalisation SMQS D7',
                'verbose_name_plural': 'Capitalisations SMQS D7',
            },
        ),
        migrations.CreateModel(
            name='AnalyseCausesDoubleAxeD4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_principale_non_detection', models.TextField(blank=True, verbose_name='Synthèse cause principale de non-détection (D4.1)')),
                ('cause_principale_technique', models.TextField(blank=True, verbose_name='Synthèse cause principale technique / non-conformité (D4.2)')),
                ('pourquoi_non_detection', models.JSONField(blank=True, default=list, verbose_name='5 Pourquoi Non-Détection (D4.1)')),
                ('pourquoi_technique', models.JSONField(blank=True, default=list, verbose_name='5 Pourquoi Cause Technique (D4.2)')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_causes_d4', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Analyse des causes D4',
                'verbose_name_plural': 'Analyses des causes D4',
            },
        ),
        migrations.CreateModel(
            name='ActionTestD5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_action', models.TextField(verbose_name='Action test')),
                ('pilote_delai', models.CharField(blank=True, max_length=200, verbose_name='Pilote - Délai')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusion du test')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_tests', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Action test D5',
                'verbose_name_plural': 'Actions tests D5',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ActionPermanenteD6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe', models.CharField(choices=[('non_detection', 'D4.1 - Non Détection'), ('technique', 'D4.2 - Cause Technique'), ('autre', 'Autre')], default='technique', max_length=20, verbose_name="Axe d'analyse")),
                ('cause_racine', models.TextField(blank=True, verbose_name='Cause racine associée')),
                ('description', models.TextField(verbose_name='Action corrective / préventive')),
                ('pilote', models.CharField(blank=True, max_length=200, verbose_name='Pilote')),
                ('delai', models.DateField(blank=True, null=True, verbose_name='Délai')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('date_verification', models.DateField(blank=True, null=True, verbose_name='Date de vérification')),
                ('statut', models.CharField(choices=[('non_demarre', 'Non démarré'), ('en_cours', 'En cours'), ('realise', 'Réalisé'), ('verifie', 'Vérifié')], default='non_demarre', max_length=20, verbose_name='Statut')),
                ('efficace', models.BooleanField(null=True, verbose_name='Action efficace ?')),
                ('audit_poste_doc37', models.BooleanField(default=False, verbose_name='Audit de poste Doc 37 réalisé ?')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_permanentes', to='reclamation_client.reclamationclient', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Action permanente D6',
                'verbose_name_plural': 'Actions permanentes D6',
                'ordering': ['ordre'],
            },
        ),
    ]
