# Generated by Django 4.2.30 on 2026-09-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamationclient',
            name='mode_traitement',
            field=models.CharField(choices=[('8D', 'Rapport 8D (Doc 83)'), ('DOC05', "Fiche d'incident simplifiée (Doc 05)"), ('DOC05_FAI', "Fiche d'Amélioration Interne (Doc 05)")], default='8D', max_length=10, verbose_name='Support de traitement'),
        ),
        migrations.CreateModel(
            name='FicheIncidentDoc05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redacteur', models.CharField(blank=True, max_length=200, verbose_name='Rédacteur de la fiche')),
                ('date_detection', models.DateField(blank=True, null=True, verbose_name='Date de détection la non-conformité')),
                ('date_ouverture', models.DateField(blank=True, null=True, verbose_name="Date de l'ouverture de la fiche")),
                ('site_concerne', models.CharField(blank=True, max_length=200, verbose_name='Site concerné')),
                ('evenement_qualite', models.BooleanField(default=True, verbose_name='Qualité')),
                ('evenement_securite', models.BooleanField(default=False, verbose_name='Sécurité')),
                ('evenement_environnement', models.BooleanField(default=False, verbose_name='Environnement')),
                ('quoi_reponse', models.TextField(blank=True, verbose_name='QUOI - Réponse pour décrire le problème')),
                ('qui_reponse', models.TextField(blank=True, verbose_name='QUI - Réponse pour décrire le problème')),
                ('ou_reponse', models.TextField(blank=True, verbose_name='OÙ - Réponse pour décrire le problème')),
                ('quand_reponse', models.TextField(blank=True, verbose_name='QUAND - Réponse pour décrire le problème')),
                ('comment_reponse', models.TextField(blank=True, verbose_name='COMMENT - Réponse pour décrire le problème')),
                ('combien_reponse', models.TextField(blank=True, verbose_name='COMBIEN - Réponse pour décrire le problème')),
                ('autre_reponse', models.TextField(blank=True, verbose_name='AUTRE - Informations utiles')),
                ('motif_non_conformite', models.TextField(blank=True, verbose_name='Motif de la non-conformité')),
                ('pourquoi_chains', models.JSONField(blank=True, default=list, verbose_name='5 Pourquoi Chains (Doc 05)')),
                ('deja_signale', models.BooleanField(default=False, verbose_name='Ce problème a-t-il déjà été signalé ?')),
                ('deja_signale_details', models.CharField(blank=True, max_length=255, verbose_name='Date / Période si déjà signalé')),
                ('particularites_changements', models.BooleanField(default=False, verbose_name='Particularités / changements intervenus ?')),
                ('particularites_details', models.TextField(blank=True, verbose_name='Lesquels si particularités')),
                ('risque_similaire', models.BooleanField(default=False, verbose_name='Risque similaire sur autre produit/secteur ?')),
                ('risque_similaire_details', models.CharField(blank=True, max_length=255, verbose_name='Où si risque similaire')),
                ('mesures_immediates', models.JSONField(blank=True, default=list, verbose_name='Mesures immédiates (Doc 05)')),
                ('actions_correctives', models.JSONField(blank=True, default=list, verbose_name='Actions correctives retenues (Doc 05)')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_doc05', to='reclamation_client.reclamationclient', verbose_name='Réclamation / Incident')),
            ],
            options={
                'verbose_name': 'Fiche Incident / FAI Doc 05',
                'verbose_name_plural': 'Fiches Incidents / FAI Doc 05',
            },
        ),
    ]
