# Generated by Django 4.2.30 on 2026-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation_client', '0002_alter_reclamationclient_mode_traitement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamationclient',
            options={'verbose_name': 'Réclamation Client', 'verbose_name_plural': 'Réclamations Clients'},
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='mode_traitement',
            field=models.CharField(choices=[('8D', 'Rapport 8D'), ('DOC05', "Fiche d'incident (Doc 05)"), ('DOC05_FAI', "Fiche d'incident / FAI")], default='8D', max_length=10, verbose_name='Support de traitement'),
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='type_signalement',
            field=models.CharField(choices=[('R', 'Réclamation (R)'), ('I', 'Incident (I)'), ('AI', 'Amélioration (AI)')], default='R', max_length=5, verbose_name='Type de signalement'),
        ),
    ]
