# Generated by Django 5.2.14 on 2026-07-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessusService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Processus / Service',
                'verbose_name_plural': 'Processus / Services',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('procedure', 'Procédure'), ('mode_operatoire', 'Mode opératoire'), ('formulaire', 'Formulaire'), ('enregistrement', 'Enregistrement'), ('associe', 'Document associé')], max_length=20, verbose_name='Type de document')),
                ('numero_ordre', models.PositiveIntegerField(verbose_name="Numéro d'ordre")),
                ('code_documentaire', models.CharField(db_index=True, editable=False, max_length=40, verbose_name='Code documentaire')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_verification', 'En vérification'), ('en_approbation', 'En approbation'), ('applicable', 'Applicable'), ('archive', 'Archivé'), ('supprime', 'Supprimé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('objet', models.TextField(blank=True, verbose_name='Objet')),
                ('domaine_application', models.TextField(blank=True, verbose_name="Domaine d'application")),
                ('definitions', models.TextField(blank=True, verbose_name='Définitions')),
                ('responsabilites', models.TextField(blank=True, verbose_name='Responsabilités')),
                ('regles_etapes', models.TextField(blank=True, verbose_name='Règles / étapes')),
                ('modalites_diffusion', models.TextField(blank=True, verbose_name='Modalités de diffusion')),
                ('modalites_modification', models.TextField(blank=True, verbose_name='Modalités de modification')),
                ('modalites_archivage', models.TextField(blank=True, verbose_name="Modalités d'archivage")),
                ('poste_service_activite', models.TextField(blank=True, verbose_name='Poste / service / activité')),
                ('prerequis', models.TextField(blank=True, verbose_name='Prérequis')),
                ('equipements_outils_logiciels', models.TextField(blank=True, verbose_name='Équipements / outils / logiciels')),
                ('etapes_detaillees', models.TextField(blank=True, verbose_name='Étapes détaillées')),
                ('points_controle', models.TextField(blank=True, verbose_name='Points de contrôle')),
                ('criteres_acceptation', models.TextField(blank=True, verbose_name="Critères d'acceptation")),
                ('consignes_securite', models.TextField(blank=True, verbose_name='Consignes de sécurité')),
                ('enregistrements_a_completer', models.TextField(blank=True, verbose_name='Enregistrements à compléter')),
                ('anomalies_actions', models.TextField(blank=True, verbose_name='Anomalies / actions à mener')),
                ('reference_documentaire', models.CharField(blank=True, max_length=120, verbose_name='Référence documentaire')),
                ('schema_collecte', models.JSONField(blank=True, default=dict, verbose_name='Schéma de collecte')),
                ('service_concerne', models.CharField(blank=True, max_length=255, verbose_name='Personne / service concerné')),
                ('visas_validations', models.TextField(blank=True, verbose_name='Visas / validations')),
                ('lien_externe', models.URLField(blank=True, verbose_name='Lien externe')),
                ('date_application', models.DateField(blank=True, null=True, verbose_name="Date d'application")),
                ('date_retrait', models.DateField(blank=True, null=True, verbose_name='Date de retrait')),
                ('motif_remplacement', models.TextField(blank=True, verbose_name='Motif de remplacement')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Suppression logique')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('processus_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='gestion_documentaire.processusservice', verbose_name='Processus / Service')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['code_documentaire', '-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('revision', 'Révision'), ('suppression', 'Suppression')], default='modification', max_length=20, verbose_name='Type de demande')),
                ('titre_propose', models.CharField(blank=True, max_length=255, verbose_name='Titre proposé')),
                ('type_document_propose', models.CharField(blank=True, choices=[('procedure', 'Procédure'), ('mode_operatoire', 'Mode opératoire'), ('formulaire', 'Formulaire'), ('enregistrement', 'Enregistrement'), ('associe', 'Document associé')], max_length=20, verbose_name='Type de document proposé')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('impacts', models.TextField(blank=True, verbose_name='Impacts')),
                ('urgence', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20, verbose_name='Urgence')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_etude', 'En étude'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('traitee', 'Traitée')], default='soumise', max_length=20, verbose_name='Statut')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire_traitement', models.TextField(blank=True, verbose_name='Commentaire de traitement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_modification', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_modification_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_modification', to='gestion_documentaire.document', verbose_name='Document concerné')),
                ('processus_service_propose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_modification', to='gestion_documentaire.processusservice', verbose_name='Processus/service proposé')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'verbose_name_plural': 'Demandes de modification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('indice', models.PositiveIntegerField(default=0, verbose_name='Indice')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_verification', 'En vérification'), ('en_approbation', 'En approbation'), ('applicable', 'Applicable'), ('archive', 'Archivé'), ('supprime', 'Supprimé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('fichier_reference', models.FileField(blank=True, null=True, upload_to='gestion_documentaire/references/', verbose_name='Fichier de référence (PDF)')),
                ('fichier_editable', models.FileField(blank=True, null=True, upload_to='gestion_documentaire/editables/', verbose_name='Fichier modifiable')),
                ('resume_changements', models.TextField(blank=True, verbose_name='Résumé des changements')),
                ('copie_non_maitrisee', models.BooleanField(default=True, verbose_name='Copie non maîtrisée')),
                ('est_supprime', models.BooleanField(default=False, verbose_name='Suppression logique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_application', models.DateField(blank=True, null=True, verbose_name="Date d'application")),
                ('date_retrait', models.DateField(blank=True, null=True, verbose_name='Date de retrait')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gestion_documentaire.document', verbose_name='Document')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_documents_redigees', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur')),
            ],
            options={
                'verbose_name': 'Version document',
                'verbose_name_plural': 'Versions documents',
                'ordering': ['document', '-version', '-indice'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('identification_besoin', 'Identification du besoin'), ('verification_equivalence', 'Vérification document équivalent'), ('determination_type', 'Détermination du type'), ('redaction', 'Rédaction'), ('verification_contenu', 'Vérification du contenu'), ('approbation', 'Approbation'), ('codification', 'Codification'), ('diffusion', 'Diffusion'), ('archivage', 'Archivage'), ('suppression', 'Suppression'), ('transition_statut', 'Transition de statut')], max_length=40, verbose_name="Type d'action")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('ancien_statut', models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('en_verification', 'En vérification'), ('en_approbation', 'En approbation'), ('applicable', 'Applicable'), ('archive', 'Archivé'), ('supprime', 'Supprimé')], max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('en_verification', 'En vérification'), ('en_approbation', 'En approbation'), ('applicable', 'Applicable'), ('archive', 'Archivé'), ('supprime', 'Supprimé')], max_length=20, verbose_name='Nouveau statut')),
                ('donnees_action', models.JSONField(blank=True, default=dict, verbose_name="Données d'action")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date d'action")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='gestion_documentaire.document', verbose_name='Document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_validation_document', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('version_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='gestion_documentaire.versiondocument', verbose_name='Version document')),
            ],
            options={
                'verbose_name': 'Validation document',
                'verbose_name_plural': 'Validations documents',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('numero_ordre__gte', 1)), name='gd_document_numero_ordre_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('est_supprime', False), ('statut', 'applicable')), fields=('code_documentaire',), name='gd_unique_document_applicable_par_code'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('est_supprime', False), ('statut', 'applicable')), fields=('code_documentaire', 'statut'), name='gd_unique_codedoc_statut_applicable'),
        ),
        migrations.AddConstraint(
            model_name='versiondocument',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='gd_version_document_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='versiondocument',
            constraint=models.CheckConstraint(check=models.Q(('indice__gte', 0)), name='gd_version_document_indice_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='versiondocument',
            constraint=models.UniqueConstraint(fields=('document', 'version', 'indice'), name='gd_unique_version_indice_par_document'),
        ),
        migrations.AddConstraint(
            model_name='versiondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('est_supprime', False), ('statut', 'applicable')), fields=('document',), name='gd_unique_version_applicable_par_document'),
        ),
    ]
