# Generated by Django 4.2.30 on 2026-07-14 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gestion_documentaire.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_section_responsable_n1_and_more'),
        ('gestion_documentaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierDocumentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('couleur', models.CharField(default='#E4A11B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Couleur hexadécimale invalide.')], verbose_name='Couleur')),
                ('acces_restreint', models.BooleanField(default=False, verbose_name="Limiter l'accès")),
                ('roles_autorises', models.JSONField(blank=True, default=list, verbose_name='Rôles autorisés')),
                ('actions_autorisees', models.JSONField(blank=True, default=list, verbose_name='Actions autorisées')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_documentaires_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_dossiers', to='gestion_documentaire.dossierdocumentaire', verbose_name='Dossier parent')),
                ('sections_autorisees', models.ManyToManyField(blank=True, related_name='dossiers_documentaires_autorises', to='accounts.section')),
                ('societes_autorisees', models.ManyToManyField(blank=True, related_name='dossiers_documentaires_autorises', to='accounts.societe')),
                ('utilisateurs_autorises', models.ManyToManyField(blank=True, related_name='dossiers_documentaires_autorises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier documentaire',
                'verbose_name_plural': 'Dossiers documentaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FichierBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(max_length=500, upload_to=gestion_documentaire.models.fichier_bibliotheque_upload_to)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('taille', models.PositiveBigIntegerField(default=0, verbose_name='Taille')),
                ('type_mime', models.CharField(blank=True, max_length=120)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers_documentaires_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='gestion_documentaire.dossierdocumentaire', verbose_name='Dossier')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RegleAccesDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_autorisees', models.JSONField(blank=True, default=list)),
                ('roles_autorises', models.JSONField(blank=True, default=list)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_acces', to='gestion_documentaire.dossierdocumentaire')),
                ('sections_autorisees', models.ManyToManyField(blank=True, related_name='regles_dossiers_autorisees', to='accounts.section')),
                ('societes_autorisees', models.ManyToManyField(blank=True, related_name='regles_dossiers_autorisees', to='accounts.societe')),
                ('utilisateurs_autorises', models.ManyToManyField(blank=True, related_name='regles_dossiers_autorisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='DemandeModification',
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='gestion_documentaire.dossierdocumentaire', verbose_name='Dossier'),
        ),
        migrations.AddConstraint(
            model_name='fichierbibliotheque',
            constraint=models.UniqueConstraint(fields=('dossier', 'nom'), name='gd_unique_fichier_nom_par_dossier'),
        ),
        migrations.AddConstraint(
            model_name='fichierbibliotheque',
            constraint=models.UniqueConstraint(condition=models.Q(('dossier__isnull', True)), fields=('nom',), name='gd_unique_fichier_nom_racine'),
        ),
        migrations.AddConstraint(
            model_name='dossierdocumentaire',
            constraint=models.UniqueConstraint(fields=('parent', 'nom'), name='gd_unique_dossier_nom_par_parent'),
        ),
        migrations.AddConstraint(
            model_name='dossierdocumentaire',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('nom',), name='gd_unique_dossier_nom_racine'),
        ),
    ]
