# Generated by Django 5.2.2 on 2026-08-05 13:58

import django.db.models.deletion
import gestion_documentaire.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_section_responsable_n1_and_more'),
        ('gestion_documentaire', '0002_dossierdocumentaire_fichierbibliotheque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom', models.CharField(max_length=180, verbose_name='Nom du processus')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ce', models.ManyToManyField(blank=True, related_name='processus_comme_ce', to=settings.AUTH_USER_MODEL, verbose_name='CE affectés')),
                ('ro', models.ManyToManyField(blank=True, related_name='processus_comme_ro', to=settings.AUTH_USER_MODEL, verbose_name='RO affectés')),
                ('rs', models.ManyToManyField(blank=True, related_name='processus_comme_rs', to=settings.AUTH_USER_MODEL, verbose_name='RS affectés')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processus', to='accounts.societe', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Processus',
                'verbose_name_plural': 'Processus',
                'ordering': ['societe', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de l’indicateur')),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel'), ('glissant_12_mois', 'Glissant sur 12 mois')], max_length=30, verbose_name='Périodicité')),
                ('mode_agregation', models.CharField(choices=[('somme', 'Somme'), ('moyenne', 'Moyenne'), ('derniere_valeur', 'Dernière valeur'), ('aucune', 'Aucune agrégation')], max_length=30, verbose_name='Mode d’agrégation')),
                ('formats_chart_disponibles', models.JSONField(blank=True, default=list, validators=[gestion_documentaire.models.validate_formats_chart], verbose_name='Formats de graphiques disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='gestion_documentaire.processus', verbose_name='Processus')),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
                'ordering': ['processus__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MesureIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois')),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valeur mesurée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='gestion_documentaire.indicateur', verbose_name='Indicateur')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_indicateurs_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
            ],
            options={
                'verbose_name': 'Mesure d’indicateur',
                'verbose_name_plural': 'Mesures d’indicateurs',
                'ordering': ['indicateur__code', '-annee', '-mois'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mois__isnull', False)), fields=('indicateur', 'annee', 'mois'), name='unique_mesure_mensuelle_indicateur'), models.UniqueConstraint(condition=models.Q(('mois__isnull', True)), fields=('indicateur', 'annee'), name='unique_mesure_annuelle_indicateur')],
            },
        ),
        migrations.CreateModel(
            name='ObjectifIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('valeur_objectif', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valeur de l’objectif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='gestion_documentaire.indicateur', verbose_name='Indicateur')),
            ],
            options={
                'verbose_name': 'Objectif d’indicateur',
                'verbose_name_plural': 'Objectifs d’indicateurs',
                'ordering': ['-annee', 'indicateur__code'],
                'constraints': [models.UniqueConstraint(fields=('indicateur', 'annee'), name='unique_objectif_par_indicateur_annee')],
            },
        ),
        migrations.AddConstraint(
            model_name='processus',
            constraint=models.UniqueConstraint(fields=('societe', 'code'), name='unique_code_processus_par_societe'),
        ),
        migrations.AddConstraint(
            model_name='indicateur',
            constraint=models.UniqueConstraint(fields=('processus', 'code'), name='unique_code_indicateur_par_processus'),
        ),
    ]
