# Generated by Django 5.2.2 on 2026-08-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_section_responsable_n1_and_more'),
        ('gestion_documentaire', '0003_processus_indicateur_mesureindicateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processus',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processus', to='accounts.societe', verbose_name='Société'),
        ),
    ]
