# Generated by Django 4.2.30 on 2026-08-07 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_section_responsable_n1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_documentaire', '0004_alter_processus_societe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processus',
            options={'ordering': ['code'], 'verbose_name': 'Processus', 'verbose_name_plural': 'Processus'},
        ),
        migrations.RemoveConstraint(
            model_name='processus',
            name='unique_code_processus_par_societe',
        ),
        migrations.RemoveField(
            model_name='processus',
            name='ce',
        ),
        migrations.RemoveField(
            model_name='processus',
            name='ro',
        ),
        migrations.RemoveField(
            model_name='processus',
            name='rs',
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='mode_agregation',
            field=models.CharField(choices=[('somme', 'Somme'), ('moyenne', 'Moyenne'), ('minimum', 'Minimum'), ('maximum', 'Maximum'), ('nombre', 'Nombre'), ('derniere_valeur', 'Dernière valeur')], default='somme', max_length=30, verbose_name='Mode d’agrégation'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='periodicite',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=30, verbose_name='Périodicité'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mesureindicateur',
            name='annee',
            field=models.PositiveIntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='mesureindicateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mesureindicateur',
            name='saisie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par'),
        ),
        migrations.AlterField(
            model_name='mesureindicateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='objectifindicateur',
            name='annee',
            field=models.PositiveIntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='objectifindicateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='objectifindicateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processus',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='processus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processus',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processus', to='accounts.societe', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='processus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processus',
            name='CE',
            field=models.ManyToManyField(blank=True, related_name='processus_CE', to=settings.AUTH_USER_MODEL, verbose_name='CE affectés'),
        ),
        migrations.AddField(
            model_name='processus',
            name='RO',
            field=models.ManyToManyField(blank=True, related_name='processus_RO', to=settings.AUTH_USER_MODEL, verbose_name='RO affectés'),
        ),
        migrations.AddField(
            model_name='processus',
            name='RS',
            field=models.ManyToManyField(blank=True, related_name='processus_RS', to=settings.AUTH_USER_MODEL, verbose_name='RS affectés'),
        ),
    ]
