# Generated by Django 4.2.30 on 2026-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentaire', '0005_alter_processus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='sens_objectif',
            field=models.CharField(choices=[('atteindre', 'À atteindre / dépasser'), ('ne_pas_depasser', 'À ne pas dépasser')], default='atteindre', max_length=30, verbose_name='Sens de l’objectif'),
        ),
    ]
