# Generated by Django 4.2.30 on 2026-08-07 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_documentaire', '0006_indicateur_sens_objectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='mode_calcul',
            field=models.CharField(choices=[('automatique', 'Calcul automatique à partir des composantes'), ('manuel', 'Saisie manuelle du réalisé consolidé')], default='automatique', max_length=30, verbose_name='Mode de calcul / saisie'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='periodicite',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel'), ('glissant_12_mois', 'Glissant sur 12 mois')], default='mensuel', max_length=30, verbose_name='Périodicité'),
        ),
        migrations.CreateModel(
            name='RealiseConsolideIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_reference', models.PositiveIntegerField(verbose_name='Année de référence')),
                ('mois_reference', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois de référence')),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valeur du réalisé consolidé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realises_consolides', to='gestion_documentaire.indicateur', verbose_name='Indicateur')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': "Réalisé consolidé d'indicateur",
                'verbose_name_plural': "Réalisés consolidés d'indicateurs",
                'ordering': ['indicateur__code', '-annee_reference', '-mois_reference'],
            },
        ),
        migrations.AddConstraint(
            model_name='realiseconsolideindicateur',
            constraint=models.UniqueConstraint(fields=('indicateur', 'annee_reference', 'mois_reference'), name='unique_realise_consolide_indicateur_periode'),
        ),
    ]
