# Generated by Django 4.2.30 on 2026-08-07 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gestion_documentaire.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_documentaire', '0007_indicateur_mode_calcul_alter_indicateur_periodicite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposanteIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, validators=[gestion_documentaire.models.validate_code_composante], verbose_name='Code de la composante')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé de la composante')),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Composante d'indicateur",
                'verbose_name_plural': "Composantes d'indicateurs",
                'ordering': ['indicateur', 'ordre', 'code'],
            },
        ),
        migrations.AddField(
            model_name='indicateur',
            name='formule',
            field=models.CharField(blank=True, max_length=255, verbose_name='Formule de calcul'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='mode_calcul',
            field=models.CharField(choices=[('automatique', 'Calcul automatique à partir des composantes'), ('manuel', 'Saisie manuelle du réalisé consolidé'), ('formule', 'Calcul automatique par formule')], default='automatique', max_length=30, verbose_name='Mode de calcul / saisie'),
        ),
        migrations.CreateModel(
            name='ValeurComposanteIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valeur mesurée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='gestion_documentaire.composanteindicateur', verbose_name='Composante')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
            ],
            options={
                'verbose_name': 'Valeur de composante',
                'verbose_name_plural': 'Valeurs de composantes',
                'ordering': ['composante', '-annee', '-mois'],
            },
        ),
        migrations.AddField(
            model_name='composanteindicateur',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composantes', to='gestion_documentaire.indicateur', verbose_name='Indicateur'),
        ),
        migrations.AddConstraint(
            model_name='valeurcomposanteindicateur',
            constraint=models.UniqueConstraint(fields=('composante', 'annee', 'mois'), name='unique_valeur_composante_periode'),
        ),
        migrations.AddConstraint(
            model_name='composanteindicateur',
            constraint=models.UniqueConstraint(fields=('indicateur', 'code'), name='unique_code_composante_par_indicateur'),
        ),
    ]
