# Generated by Django 4.2.30 on 2026-08-27 10:01

from django.db import migrations, models
import django.db.models.deletion


def migrer_processus_service_vers_processus(apps, schema_editor):
    Document = apps.get_model("gestion_documentaire", "Document")
    Processus = apps.get_model("gestion_documentaire", "Processus")

    for doc in Document.objects.filter(processus_service__isnull=False):
        old_ps = doc.processus_service
        if old_ps and old_ps.code:
            code_clean = old_ps.code.strip()
            # Chercher si un Processus existe déjà avec ce code (indifférent à la casse)
            proc = Processus.objects.filter(code__iexact=code_clean).first()
            if not proc:
                # Si aucun équivalent n'existe, on le crée sans créer de doublons
                proc = Processus.objects.create(
                    code=code_clean.upper(),
                    nom=getattr(old_ps, "libelle", code_clean),
                    description=getattr(old_ps, "description", "") or "",
                    is_active=getattr(old_ps, "actif", True),
                )
            doc.processus = proc
            doc.save(update_fields=["processus"])


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_documentaire", "0008_composanteindicateur_indicateur_formule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="gestion_documentaire.processus",
                verbose_name="Processus",
            ),
        ),
        migrations.RunPython(
            migrer_processus_service_vers_processus,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="document",
            name="processus_service",
        ),
        migrations.DeleteModel(
            name="ProcessusService",
        ),
    ]
