# Generated by Django 5.2.14 on 2026-06-30 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=500, verbose_name='Adresse')),
                ('contact_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du contact')),
                ('contact_mail', models.EmailField(blank=True, max_length=254, verbose_name='E-mail du contact')),
                ('contact_tel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du contact')),
                ('statut_evaluation', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name="Statut d'évaluation")),
                ('pris_en_compte', models.BooleanField(default=True, verbose_name='Pris en compte')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalogue/', verbose_name='Photo')),
                ('type_article', models.CharField(choices=[('materiel', 'Matériel'), ('immateriel', 'Immatériel')], max_length=20, verbose_name="Type d'article")),
                ('categorie', models.CharField(choices=[('fourniture_bureau', 'Fourniture bureau'), ('outillage', 'Outillage'), ('epi', 'EPI'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_catalogue', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Article du catalogue',
                'verbose_name_plural': 'Articles du catalogue',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='OffreFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_propose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif proposé')),
                ('reference_chez_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence chez le fournisseur')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='achats.articlecatalogue', verbose_name='Article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='achats.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Offre fournisseur',
                'verbose_name_plural': 'Offres fournisseurs',
                'unique_together': {('article', 'fournisseur')},
            },
        ),
    ]
