# Generated by Django 5.2.14 on 2026-06-30 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_section_options_rename_nom_section_nom'),
        ('achats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('delai_souhaite', models.DateField(blank=True, null=True, verbose_name='Délai souhaité')),
                ('adresse_livraison', models.CharField(max_length=255, verbose_name='Adresse de livraison')),
                ('categorie', models.CharField(choices=[('fourniture_bureau', 'Fourniture bureau'), ('outillage', 'Outillage'), ('epi', 'EPI'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('est_demande_de_prix', models.BooleanField(default=False, help_text='Demande de prix uniquement, pour étude/devis/consultation', verbose_name='Demande de prix uniquement')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('en_cours_devis', 'En cours de devis'), ('en_validation_n1', 'Validation N1'), ('en_validation_n2', 'Validation N2'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('commandee', 'Commandée'), ('receptionnee', 'Réceptionnée'), ('cloturee', 'Clôturée')], default='brouillon', max_length=30, verbose_name='Statut')),
                ('total_commande_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total commande HT')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_achat', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('section_analytique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_achat', to='accounts.section', verbose_name='Section analytique')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hors_catalogue', models.BooleanField(default=False, verbose_name='Hors catalogue')),
                ('nouvelle_designation', models.CharField(blank=True, max_length=255, verbose_name='Nouvelle désignation')),
                ('nouvelle_description', models.TextField(blank=True, verbose_name='Nouvelle description')),
                ('nouvelle_photo', models.ImageField(blank=True, null=True, upload_to='nouveaux_articles/', verbose_name='Photo du nouvel article')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('qte_stock', models.PositiveIntegerField(default=0, verbose_name='Qté stock')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Renseigné par le service achat', max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix total')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('engin_concerne', models.CharField(blank=True, max_length=255, verbose_name='Engin (si concerné)')),
                ('article_catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_demande', to='achats.articlecatalogue', verbose_name='Article du catalogue')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.demandeachat', verbose_name='Demande')),
                ('fournisseur_retenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_retenues', to='achats.fournisseur', verbose_name='Fournisseur retenu')),
            ],
            options={
                'verbose_name': "Ligne de demande d'achat",
                'verbose_name_plural': "Lignes de demande d'achat",
            },
        ),
    ]
