# Generated by Django 5.2.14 on 2026-06-30 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_demandeachat_lignedemandeachat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(1, 'Demandeur'), (2, 'Directeur de Pôle'), (3, 'Directeur Général')], verbose_name='Niveau')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('modification_demandee', 'Modification demandée')], default='en_attente', max_length=30, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_action', models.DateTimeField(blank=True, null=True, verbose_name="Date d'action")),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='achats.demandeachat', verbose_name='Demande')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_validation_achat', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Étape de validation',
                'verbose_name_plural': 'Étapes de validation',
                'ordering': ['demande', 'niveau'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_propose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix proposé')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('document', models.FileField(blank=True, null=True, upload_to='devis/', verbose_name='Document')),
                ('delai_livraison_propose', models.CharField(blank=True, max_length=255, verbose_name='Délai de livraison proposé')),
                ('est_choisi', models.BooleanField(default=False, verbose_name='Devis retenu')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_achats', to='achats.fournisseur', verbose_name='Fournisseur')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='achats.lignedemandeachat', verbose_name='Ligne')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['ligne_id', 'date_saisie', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('est_choisi', True)), fields=('ligne',), name='unique_devis_choisi_par_ligne')],
            },
        ),
    ]
