# Generated by Django 5.2.14 on 2026-06-30 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_etapevalidation_devis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionMarchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateField(auto_now_add=True, verbose_name='Date de réception')),
                ('conforme_quantite_etat', models.BooleanField(default=True, verbose_name='Conforme en quantité et état')),
                ('c1_reponse_demande_prix', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C1 Réponse aux demandes de prix')),
                ('c2_livraisons', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C2 Livraisons')),
                ('c3_disponibilite', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C3 Disponibilité')),
                ('c4_qualite_utilisation', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name="C4 Qualité à l'utilisation")),
                ('c5_qualite_reception', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C5 Qualité à la réception')),
                ('c6_information_produit', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C6 Information sur le produit')),
                ('c7_reglement_litiges', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C7 Règlement des litiges')),
                ('c8_couts', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C8 Coûts')),
                ('c9_communication', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='C9 Communication')),
                ('score_calcule', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Score calculé')),
                ('note_calculee', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], editable=False, max_length=1, verbose_name='Note calculée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='achats.demandeachat', verbose_name='Demande')),
                ('receptionne_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_marchandise', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par')),
            ],
            options={
                'verbose_name': 'Réception marchandise',
                'verbose_name_plural': 'Réceptions marchandise',
                'ordering': ['-date_creation'],
            },
        ),
    ]
