# Generated by Django 5.2.14 on 2026-06-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_receptionmarchandise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dysfonctionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signalement', models.DateField(auto_now_add=True, verbose_name='Date de signalement')),
                ('heure_signalement', models.TimeField(verbose_name='Heure de signalement')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dysfonctionnements/', verbose_name='Photo')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de traitement'), ('clos', 'Clos')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('plan_action', models.TextField(blank=True, help_text="Plan d'action du prestataire pour remédier au dysfonctionnement", verbose_name="Plan d'action")),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dysfonctionnements', to='achats.demandeachat', verbose_name='Demande')),
                ('reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dysfonctionnements', to='achats.receptionmarchandise', verbose_name='Réception')),
                ('signale_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dysfonctionnements_signales', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Dysfonctionnement',
                'verbose_name_plural': 'Dysfonctionnements',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('ca_annuel', models.DecimalField(blank=True, decimal_places=2, help_text="CA réalisé avec ce fournisseur sur l'année", max_digits=12, null=True, verbose_name='CA annuel')),
                ('pris_en_compte', models.BooleanField(default=True, help_text='Selon critères P03 chapitre 5 : exclut assurances, hôtels, refacturations clients', verbose_name='Pris en compte')),
                ('nb_receptions_evaluees', models.PositiveIntegerField(default=0, verbose_name='Nb réceptions évaluées')),
                ('score_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score moyen')),
                ('note', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Note')),
                ('nb_dysfonctionnements', models.PositiveIntegerField(default=0, verbose_name='Nb dysfonctionnements')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date de calcul')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='achats.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Évaluation fournisseur',
                'verbose_name_plural': 'Évaluations fournisseurs',
                'ordering': ['-annee', '-score_moyen'],
                'unique_together': {('fournisseur', 'annee')},
            },
        ),
    ]
