# Generated by Django 5.2.14 on 2026-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_dysfonctionnement_evaluationfournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecatalogue',
            name='prix_reference_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de reference HT'),
        ),
        migrations.AddField(
            model_name='articlecatalogue',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
    ]
