# Generated by Django 5.2.14 on 2026-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_articlecatalogue_prix_reference_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='reference_fournisseur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur'),
        ),
    ]
