# Generated by Django 5.2.5 on 2026-07-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("achats", "0007_fournisseur_reference_fournisseur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationValidationSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_creation", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ("date_modification", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_validation_achat",
                        to="accounts.section",
                        verbose_name="Section",
                    ),
                ),
                (
                    "validateur_n1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations_achat_n1_configurees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validateur N1",
                    ),
                ),
                (
                    "validateur_n2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations_achat_n2_configurees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validateur N2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration validation section",
                "verbose_name_plural": "Configurations validation sections",
                "ordering": ["section__Nom"],
            },
        ),
    ]
