# Generated by Django 5.1.5 on 2026-05-26 20:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_c_user_is_rc_user_is_admin_user_societe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure')),
                ('type', models.CharField(choices=[('action', 'Action'), ('event', 'Événement'), ('enquete', 'Enquête')], max_length=10, verbose_name='Type de notification')),
                ('lien_id', models.PositiveIntegerField(verbose_name="ID de l'action ou de l'événement lié")),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fr', models.TextField(default='', verbose_name='Intitulé de la question (Français)')),
                ('question_en', models.TextField(default='', verbose_name='Intitulé de la question (Anglais)')),
                ('question_de', models.TextField(blank=True, default='', verbose_name='Intitulé de la question (Allemand)')),
                ('type', models.CharField(choices=[('closed', 'Échelle'), ('ouinon', 'Oui / Non / Peut-être'), ('open', 'Commentaire'), ('note', 'Note (1-10)')], default='closed', max_length=20, verbose_name='Type de question')),
                ('obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateField(verbose_name='Date de creation')),
                ('date_modification', models.DateField(blank=True, null=True, verbose_name='Date de modification')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_rappel', models.DateField(blank=True, null=True, verbose_name='Date de rappel')),
                ('date_reponse', models.DateField(blank=True, null=True, verbose_name='Date de reponse')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email destinataire')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Répondu complètement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquetes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Enquête',
                'verbose_name_plural': 'Enquêtes',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('secteur_activite', models.CharField(max_length=100, verbose_name="Secteur d'Activité")),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_conversion', models.DateTimeField(blank=True, null=True, verbose_name='Date Conversion')),
                ('is_CLT', models.BooleanField(default=False, verbose_name='Est Client')),
                ('is_Prospect', models.BooleanField(default=False, verbose_name='Est Prospect')),
                ('is_Concurent', models.BooleanField(default=False, verbose_name='Est Concurrent')),
                ('num_compte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de compte')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.societe', verbose_name='Société')),
            ],
        ),
        migrations.CreateModel(
            name='EnqueteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de', 'Deutsch')], default='fr', max_length=2, verbose_name='Language')),
                ('enquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='prospection.enquete')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospection.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='enquete',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospection.entreprise', verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure')),
                ('date_heure_planifie', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date et Heure Planifiés')),
                ('date_heure_realiser', models.DateTimeField(blank=True, null=True, verbose_name='Date et Heure Réalisés')),
                ('compte_rendu', models.TextField(verbose_name='Compte Rendu')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('is_Appel', models.BooleanField(default=False, verbose_name='est appel')),
                ('is_Email', models.BooleanField(default=False, verbose_name='est email')),
                ('is_RV', models.BooleanField(default=False, verbose_name='est rendez-vous')),
                ('etat', models.CharField(blank=True, max_length=50, null=True, verbose_name='État')),
                ('reminder_sent_1day', models.BooleanField(default=False, verbose_name='Rappel 1 jour envoyé')),
                ('reminder_sent_1hour', models.BooleanField(default=False, verbose_name='Rappel 1 heure envoyé')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('pilote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_pilotees', to=settings.AUTH_USER_MODEL, verbose_name='Pilote')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.societe', verbose_name='Société')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='prospection.entreprise', verbose_name='Entreprise/Client')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_heure_planifie', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et Heure Planifiés')),
                ('date_heure_realiser', models.DateTimeField(blank=True, null=True, verbose_name='Date et Heure Réalisés')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('secteur_activite', models.CharField(max_length=100, verbose_name='Secteur Activité')),
                ('etat', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('', '-')], default='', max_length=50, verbose_name='État')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='interne', max_length=10, verbose_name='Type')),
                ('categorie', models.CharField(blank=True, choices=[('foire', 'Foire'), ('salon', 'Salon'), ('conference', 'Conference'), ('seminaire', 'Seminaire')], max_length=20, verbose_name='Catégorie')),
                ('reminder_sent_1day', models.BooleanField(default=False, verbose_name='Rappel 1 jour envoyé')),
                ('reminder_sent_1hour', models.BooleanField(default=False, verbose_name='Rappel 1 heure envoyé')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospection.entreprise', verbose_name='Entreprise')),
                ('pilote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_pilotes', to=settings.AUTH_USER_MODEL, verbose_name='Pilote')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.societe', verbose_name='Société')),
            ],
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.TextField(verbose_name='Registration token')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
            },
        ),
        migrations.CreateModel(
            name='NotificationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospection.notification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='prospection_notifications', through='prospection.NotificationUtilisateur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs'),
        ),
        migrations.CreateModel(
            name='ProspectResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de recherche')),
                ('query', models.TextField(blank=True, null=True, verbose_name='Requête utilisée')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Résumé des trouvailles')),
                ('raw_result', models.TextField(blank=True, null=True, verbose_name='Résultat brut')),
                ('confidence', models.CharField(choices=[('high', 'Fiabilité élevée'), ('medium', 'Fiabilité moyenne'), ('low', 'Fiabilité faible'), ('none', 'Échec')], default='medium', max_length=10, verbose_name='Niveau de confiance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_research_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_researches', to='prospection.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('website', 'Site web'), ('social', 'Réseau social'), ('address', 'Adresse'), ('note', 'Note')], max_length=20, verbose_name='Type')),
                ('value', models.CharField(max_length=500, verbose_name='Valeur')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_infos', to='prospection.entreprise', verbose_name='Entreprise')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='prospection.prospectresearch', verbose_name='Recherche')),
            ],
        ),
        migrations.AddField(
            model_name='enquete',
            name='questions',
            field=models.ManyToManyField(related_name='enquetes_set', to='prospection.question'),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(help_text='Texte, Oui/Non, note ou choix selon le type de la question', max_length=500, verbose_name='Valeur de la réponse')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_reponses', to='prospection.entreprise', verbose_name='Client')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='prospection.enquete', verbose_name='Enquête')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='prospection.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.CreateModel(
            name='Swot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('force', 'Force'), ('faiblesse', 'Faiblesse'), ('opportunite', 'Opportunité'), ('menace', 'Menace')], max_length=50, verbose_name='Type')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('axe', models.CharField(choices=[('commercial', 'Commercial'), ('financiere', 'Financier'), ('exploitation', 'Exploitation'), ('rh', 'Ressources humaines'), ('technologique', 'Technologique'), ('autre', 'Autre')], max_length=50, verbose_name='Axe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swots_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entreprise', models.ForeignKey(limit_choices_to={'is_Concurent': True}, on_delete=django.db.models.deletion.CASCADE, to='prospection.entreprise', verbose_name='Entreprise Concurrente')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.societe', verbose_name='Société')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(condition=models.Q(('num_compte__isnull', True), _negated=True), fields=('societe', 'num_compte'), name='unique_num_compte_par_societe'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['reminder_sent_1day'], name='prospection_reminde_ccdcae_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['reminder_sent_1hour'], name='prospection_reminde_b9ca57_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['reminder_sent_1day'], name='prospection_reminde_a28399_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['reminder_sent_1hour'], name='prospection_reminde_4cd2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['categorie'], name='prospection_categor_768efa_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['type'], name='prospection_type_6699e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationutilisateur',
            unique_together={('notification', 'utilisateur')},
        ),
        migrations.AddIndex(
            model_name='prospectinfo',
            index=models.Index(fields=['type'], name='prospection_type_d74239_idx'),
        ),
        migrations.AddConstraint(
            model_name='prospectinfo',
            constraint=models.UniqueConstraint(fields=('entreprise', 'type', 'value'), name='unique_info_per_entreprise'),
        ),
    ]
