# Generated by Django 5.1.5 on 2026-05-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_C',
            field=models.BooleanField(default=False, verbose_name='Est Commercial'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_RC',
            field=models.BooleanField(default=False, verbose_name='Est Responsable Commercial'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Est Admin Multi-Société'),
        ),
        migrations.AddField(
            model_name='user',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerciaux', to='accounts.societe', verbose_name='Société principale'),
        ),
        migrations.AddField(
            model_name='user',
            name='societes',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_admins', to='accounts.societe', verbose_name='Sociétés (Admin Multi-Société)'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
