# Generated by Django 5.2.14 on 2026-06-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_customer_section_fields_user_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('Nom',), 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='nom',
            new_name='Nom',
        ),
    ]
