# Generated by Django 5.2.14 on 2026-06-30 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_section_options_rename_nom_section_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='responsable_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_validation_n1', to=settings.AUTH_USER_MODEL, verbose_name='Responsable N1'),
        ),
        migrations.AddField(
            model_name='section',
            name='responsable_n2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_validation_n2', to=settings.AUTH_USER_MODEL, verbose_name='Responsable N2'),
        ),
    ]
