# Generated by Django 5.2.14 on 2026-07-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_section_responsable_n1_section_responsable_n2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='responsable_n1',
        ),
        migrations.RemoveField(
            model_name='section',
            name='responsable_n2',
        ),
    ]
