"""URLs du module Achats."""

from django.urls import path

from .views import (
    ArticleCatalogueCreateView,
    ArticleCatalogueDeleteView,
    ArticleCatalogueDetailView,
    ArticleCatalogueListView,
    ArticleCatalogueToggleActifView,
    ConfigurationValidationSectionView,
    ArticleCatalogueUpdateView,
    DashboardAchatsView,
    DemandeLancerValidationView,
    DemandePasserEnDevisView,
    DemandeAchatCreateView,
    DemandeAchatDetailView,
    DemandeAchatExcelDownloadView,
    DemandeAchatListView,
    DemandeTraiterValidationView,
    DemandeAchatUpdateView,
    DevisChoisirView,
    DevisCreateView,
    DevisDeleteView,
    DevisDemandesListView,
    DevisManageView,
    DevisUpdateView,
    DysfonctionnementCreateView,
    EvaluationFournisseurListView,
    FournisseurCreateView,
    FournisseurDetailView,
    FournisseurListView,
    FournisseurTogglePriseEnCompteView,
    FournisseurUpdateView,
    ReceptionCreateUpdateView,
    ReceptionListView,
    achats_roles_required,
)

app_name = "achats"

urlpatterns = [
    path("dashboard/", achats_roles_required(DashboardAchatsView.as_view()), name="dashboard"),
    path("configuration-validation/", achats_roles_required(ConfigurationValidationSectionView.as_view()), name="validation_config_section"),
    path("devis/", achats_roles_required(DevisDemandesListView.as_view()), name="devis_list"),
    path("receptions/", achats_roles_required(ReceptionListView.as_view()), name="reception_list"),
    path("evaluations/", achats_roles_required(EvaluationFournisseurListView.as_view()), name="evaluation_list"),
    path("catalogue/", achats_roles_required(ArticleCatalogueListView.as_view()), name="catalogue_list"),
    path("catalogue/ajouter/", achats_roles_required(ArticleCatalogueCreateView.as_view()), name="catalogue_create"),
    path("catalogue/<int:pk>/", achats_roles_required(ArticleCatalogueDetailView.as_view()), name="catalogue_detail"),
    path("catalogue/<int:pk>/modifier/", achats_roles_required(ArticleCatalogueUpdateView.as_view()), name="catalogue_update"),
    path("catalogue/<int:pk>/supprimer/", achats_roles_required(ArticleCatalogueDeleteView.as_view()), name="catalogue_delete"),
    path("catalogue/<int:pk>/toggle-actif/", achats_roles_required(ArticleCatalogueToggleActifView.as_view()), name="catalogue_toggle_actif"),
    path("demandes/", achats_roles_required(DemandeAchatListView.as_view()), name="demande_list"),
    path("demandes/nouvelle/", achats_roles_required(DemandeAchatCreateView.as_view()), name="demande_create"),
    path("demandes/<int:pk>/", achats_roles_required(DemandeAchatDetailView.as_view()), name="demande_detail"),
    path("demandes/<int:pk>/excel/", achats_roles_required(DemandeAchatExcelDownloadView.as_view()), name="demande_excel"),
    path("demandes/<int:pk>/modifier/", achats_roles_required(DemandeAchatUpdateView.as_view()), name="demande_update"),
    path("demandes/<int:pk>/passer-en-devis/", achats_roles_required(DemandePasserEnDevisView.as_view()), name="demande_start_devis"),
    path("demandes/<int:pk>/devis/", achats_roles_required(DevisManageView.as_view()), name="devis_manage"),
    path("demandes/<int:pk>/lancer-validation/", achats_roles_required(DemandeLancerValidationView.as_view()), name="demande_launch_validation"),
    path("demandes/<int:pk>/validation/<int:etape_pk>/traiter/", achats_roles_required(DemandeTraiterValidationView.as_view()), name="demande_validation_action"),
    path("demandes/<int:pk>/reception/", achats_roles_required(ReceptionCreateUpdateView.as_view()), name="reception_edit"),
    path("demandes/<int:pk>/dysfonctionnement/nouveau/", achats_roles_required(DysfonctionnementCreateView.as_view()), name="dysfonctionnement_create"),
    path("lignes/<int:ligne_pk>/devis/nouveau/", achats_roles_required(DevisCreateView.as_view()), name="devis_create"),
    path("devis/<int:pk>/modifier/", achats_roles_required(DevisUpdateView.as_view()), name="devis_update"),
    path("devis/<int:pk>/supprimer/", achats_roles_required(DevisDeleteView.as_view()), name="devis_delete"),
    path("devis/<int:pk>/choisir/", achats_roles_required(DevisChoisirView.as_view()), name="devis_choose"),
    path("fournisseurs/", achats_roles_required(FournisseurListView.as_view()), name="fournisseur_list"),
    path("fournisseurs/ajouter/", achats_roles_required(FournisseurCreateView.as_view()), name="fournisseur_create"),
    path("fournisseurs/<int:pk>/", achats_roles_required(FournisseurDetailView.as_view()), name="fournisseur_detail"),
    path("fournisseurs/<int:pk>/modifier/", achats_roles_required(FournisseurUpdateView.as_view()), name="fournisseur_update"),
    path("fournisseurs/<int:pk>/toggle-prise-en-compte/", achats_roles_required(FournisseurTogglePriseEnCompteView.as_view()), name="fournisseur_toggle_prise_en_compte"),
]
