# Generated by Django 5.1.5 on 2026-05-15 10:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Barème de cotation',
                'verbose_name_plural': 'Barèmes de cotation',
                'ordering': ('-note', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ChapitreNorme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=255)),
                ('num_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chapitre de norme',
                'verbose_name_plural': 'Chapitres de norme',
                'ordering': ('norme__nom', 'reference'),
            },
        ),
        migrations.CreateModel(
            name='NiveauxAttendus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Pourcentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('type_audit', models.CharField(blank=True, choices=[('INTERNE', 'Audit interne'), ('SITE', 'Audit site'), ('POSTE', 'Audit de poste'), ('EQUIPEMENT', 'Audit équipement')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Niveau attendu',
                'verbose_name_plural': 'Niveaux attendus',
            },
        ),
        migrations.CreateModel(
            name='NormeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='normes/')),
            ],
            options={
                'verbose_name': 'Norme documentaire',
                'verbose_name_plural': 'Normes documentaires',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='PreuveAttendue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
                ('code', models.CharField(blank=True, max_length=10)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreuveAttendueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de preuve attendue',
                'verbose_name_plural': 'Types de preuves attendues',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
                'ordering': ('texte',),
            },
        ),
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('chapitre_norme', models.ManyToManyField(blank=True, related_name='criteres', to='audit.chapitrenorme')),
                ('preuves_attendues', models.ManyToManyField(blank=True, related_name='criteres_preuves', to='audit.preuveattendue')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criteres', to='audit.theme')),
            ],
            options={
                'verbose_name': "Critère d'évaluation",
                'verbose_name_plural': "Critères d'évaluation",
                'ordering': ('theme', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FormulaireAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_audit', models.CharField(choices=[('INTERNE', 'Audit interne'), ('SITE', 'Audit site'), ('POSTE', 'Audit de poste'), ('EQUIPEMENT', 'Audit équipement')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulaires_audit', to='accounts.section')),
            ],
            options={
                'verbose_name': "Formulaire d'audit",
                'verbose_name_plural': "Formulaires d'audit",
                'ordering': ('section', 'type_audit', 'titre'),
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIER', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='BROUILLON', max_length=20)),
                ('date_audit', models.DateField(default=datetime.date.today)),
                ('commentaire', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_crees', to=settings.AUTH_USER_MODEL)),
                ('responsable_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits_responsable', to=settings.AUTH_USER_MODEL)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='audit.formulaireaudit')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ('-date_audit', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LigneFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_formulaire', to='audit.critereevaluation')),
                ('formulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='audit.formulaireaudit')),
            ],
            options={
                'verbose_name': 'Ligne de formulaire',
                'verbose_name_plural': 'Lignes de formulaire',
                'ordering': ('ordre', 'id'),
                'unique_together': {('formulaire', 'critere')},
            },
        ),
        migrations.AddField(
            model_name='chapitrenorme',
            name='norme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapitres', to='audit.normedocument'),
        ),
        migrations.CreateModel(
            name='ParticipantAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_externe', models.CharField(blank=True, max_length=255, null=True)),
                ('fonction', models.CharField(max_length=255)),
                ('est_auditeur_externe', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='audit.audit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant audit',
                'verbose_name_plural': 'Participants audit',
                'ordering': ('audit', 'id'),
            },
        ),
        migrations.AddField(
            model_name='preuveattendue',
            name='type_preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves', to='audit.preuveattenduetype'),
        ),
        migrations.CreateModel(
            name='ReponseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='audit/reponses/')),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='audit.audit')),
                ('cotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='audit.baremecotation')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='audit.ligneformulaire')),
            ],
            options={
                'verbose_name': 'Réponse audit',
                'verbose_name_plural': 'Réponses audit',
                'ordering': ('id',),
                'unique_together': {('audit', 'ligne')},
            },
        ),
        migrations.CreateModel(
            name='ReponseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='audit/reponses/')),
                ('reponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='audit.reponseaudit')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_forts', models.TextField(blank=True)),
                ('risques', models.TextField(blank=True)),
                ('opportunites', models.TextField(blank=True)),
                ('points_sensibles', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultat', to='audit.audit')),
                ('niveau_attendu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='audit.niveauxattendus')),
            ],
            options={
                'verbose_name': "Résultat d'audit",
                'verbose_name_plural': "Résultats d'audit",
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapitrenorme',
            unique_together={('norme', 'reference')},
        ),
    ]
