# Generated by Django 5.1.5 on 2026-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='type_conge',
            field=models.CharField(choices=[('conges_payes', 'Congés payés'), ('banque_heures', "Banque d'heures"), ('conges_anciennete', 'Congés ancienneté'), ('evenement_familial', 'Événement familial'), ('autre', 'Autre (imputation manuelle)'), ('conges_sans_solde', 'Congés sans solde')], max_length=30, verbose_name='Imputation sur'),
        ),
    ]
