# Generated by Django 5.1.5 on 2026-06-15 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0002_alter_demandeconge_type_conge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='date_validation_ro',
            field=models.DateField(blank=True, null=True, verbose_name='Date validation RO'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='date_validation_rs',
            field=models.DateField(blank=True, null=True, verbose_name='Date validation RS'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='validateur_ro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides_ro', to=settings.AUTH_USER_MODEL, verbose_name='Validateur (Responsable Opérationnel)'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='validateur_rs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides_rs', to=settings.AUTH_USER_MODEL, verbose_name='Validateur (Responsable Site)'),
        ),
    ]
