# Generated by Django 5.1.5 on 2026-06-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_customer_section_fields_user_fields'),
        ('conge', '0003_demandeconge_date_validation_ro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationChainConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('gestionnaires_ce', models.ManyToManyField(blank=True, help_text='Utilisateurs qui gèrent les demandes CE', related_name='validation_chain_ce', to=settings.AUTH_USER_MODEL, verbose_name="Gestionnaires CE (Chefs d'équipe)")),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_chain_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('notifies', models.ManyToManyField(blank=True, help_text='Utilisateurs qui reçoivent les alertes par email', related_name='validation_chain_notified', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires des notifications')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_chain_config', to='accounts.section', verbose_name='Section')),
                ('validateurs_ro', models.ManyToManyField(blank=True, help_text='Utilisateurs qui valident les demandes au niveau RO', related_name='validation_chain_ro', to=settings.AUTH_USER_MODEL, verbose_name='Validateurs RO (Responsables Opérationnels)')),
                ('validateurs_rs', models.ManyToManyField(blank=True, help_text='Utilisateurs qui valident les demandes au niveau RS', related_name='validation_chain_rs', to=settings.AUTH_USER_MODEL, verbose_name='Validateurs RS (Responsables Site)')),
            ],
            options={
                'verbose_name': 'Configuration de chaîne de validation',
                'verbose_name_plural': 'Configurations de chaînes de validation',
                'ordering': ('section__nom',),
            },
        ),
    ]
