# Generated by Django 5.1.5 on 2026-06-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0004_add_validation_chain_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationchainconfiguration',
            name='notifies',
        ),
    ]
