# Generated by Django 5.2.14 on 2026-06-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0005_remove_validationchainconfiguration_notifies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationchainconfiguration',
            options={'ordering': ('section__Nom',), 'verbose_name': 'Configuration de chaîne de validation', 'verbose_name_plural': 'Configurations de chaînes de validation'},
        ),
    ]
