# Generated by Django 5.1.5 on 2026-05-15 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accident_travail', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='accounts.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='accounts.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='accounts.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='actioncorrectiveimmédiate',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_correctives_immediates', to='accident_travail.accidenttravail', verbose_name='Accident'),
        ),
        migrations.AddField(
            model_name='analyse48h',
            name='accident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_48h', to='accident_travail.accidenttravail', verbose_name='Accident'),
        ),
        migrations.AddField(
            model_name='analyse48h',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='lap8jours',
            name='accident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lap_8j', to='accident_travail.accidenttravail', verbose_name='Accident'),
        ),
        migrations.AddField(
            model_name='actioncorrective',
            name='lap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accident_travail.lap8jours', verbose_name='LAP 8 jours'),
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_items', to='accident_travail.analyse48h', verbose_name='Analyse'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireitem',
            unique_together={('analyse', 'code')},
        ),
    ]
