# Generated by Django 5.2.14 on 2026-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='notification_brouillon_envoyee',
            field=models.BooleanField(default=False, verbose_name='Notification brouillon envoyée'),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon (à compléter)'), ('24h', 'Déclaration 24h en cours'), ('48h', 'Analyse 48h en cours'), ('8j', 'LAP 8 jours en cours'), ('cloture', 'Clôturé')], default='24h', max_length=10, verbose_name='Statut'),
        ),
    ]
