# Generated by Django 5.2.14 on 2026-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0003_accidenttravail_notification_brouillon_envoyee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse48h',
            name='soumis_le',
            field=models.DateTimeField(blank=True, help_text="Date/heure de soumission définitive de l'analyse 48h", null=True, verbose_name='Soumis le'),
        ),
        migrations.AddField(
            model_name='lap8jours',
            name='soumis_le',
            field=models.DateTimeField(blank=True, help_text='Date/heure de soumission définitive du LAP 8 jours', null=True, verbose_name='Soumis le'),
        ),
    ]
