# Generated by Django 5.2.14 on 2026-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0004_analyse48h_soumis_le_lap8jours_soumis_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='soumis_le',
            field=models.DateTimeField(blank=True, help_text='Date/heure de soumission définitive de la déclaration 24h', null=True, verbose_name='Formulaire 24h soumis le'),
        ),
    ]
