# Generated by Django 5.2.14 on 2026-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0005_add_soumis_le_to_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidenttravail',
            name='accident_constate_par',
            field=models.CharField(blank=True, choices=[('employeur', "Par l'employeur"), ('preposes', 'Par ses préposés'), ('victime', 'Décrit par la victime')], max_length=20, verbose_name='Constaté par'),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='siege_lesions',
            field=models.JSONField(blank=True, default=list, verbose_name='Siège des lésions'),
        ),
    ]
