# Generated by Django 5.2.14 on 2026-05-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0006_add_victime_constate_par_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseRacine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500, verbose_name='Cause identifiée')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_racines', to='accident_travail.analyse48h', verbose_name='Analyse 48h')),
            ],
            options={
                'verbose_name': 'Cause racine',
                'verbose_name_plural': 'Causes racines',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
