# Generated by Django 5.2.14 on 2026-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0008_add_pourquoi_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='siege_lesions_schema',
            field=models.TextField(blank=True, help_text='Image annotée (base64) du schéma corporel', verbose_name='Schéma siège des lésions'),
        ),
    ]
