# Generated by Django 5.2.14 on 2026-06-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0009_accidenttravail_siege_lesions_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidenttravail',
            name='declarant_date',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='declarant_fait_a',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='declarant_nom_prenom',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='declarant_qualite',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_adresse',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_anciennete_poste',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_contrat',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_date_embauche',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_date_naissance',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_num_immatriculation',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_profession',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_qualification',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_sexe',
        ),
        migrations.RemoveField(
            model_name='accidenttravail',
            name='victime_societe_interim',
        ),
    ]
