# Generated by Django 5.2.14 on 2026-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0010_remove_accidenttravail_declarant_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='siege_lesions_arrows_data',
            field=models.JSONField(blank=True, default=list, help_text='Coordonnées et types des flèches annotées sur le schéma corporel', verbose_name='Données des flèches du schéma'),
        ),
    ]
