# Generated by Django 5.2.14 on 2026-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_travail', '0011_accidenttravail_siege_lesions_arrows_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse48h',
            name='horaire_travail',
            field=models.CharField(blank=True, help_text='Exemple: 08:00-12:00, 14:00-18:00', max_length=100, verbose_name='Horaire de travail'),
        ),
        migrations.AddField(
            model_name='analyse48h',
            name='victime_sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='analyse48h',
            name='victime_anciennete_poste_analyse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ancienneté au poste'),
        ),
        migrations.AlterField(
            model_name='analyse48h',
            name='victime_poste_occupe',
            field=models.CharField(blank=True, max_length=200, verbose_name="Poste occupé au moment de l'accident"),
        ),
    ]
