# Generated by Django 4.2.30 on 2026-08-31 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation_client', '0001_initial'),
        ('accident_travail', '0012_analyse48h_horaire_travail_analyse48h_victime_sexe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncorrective',
            name='audit_poste_doc37',
            field=models.BooleanField(default=False, verbose_name='Audit de poste Doc 37 réalisé ?'),
        ),
        migrations.AddField(
            model_name='actioncorrective',
            name='axe',
            field=models.CharField(blank=True, choices=[('technique', 'D4.2 - Cause Technique'), ('non_detection', 'D4.1 - Non Détection'), ('autre', 'Autre')], default='technique', max_length=20, verbose_name="Axe d'analyse"),
        ),
        migrations.AddField(
            model_name='actioncorrective',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_correctives', to='reclamation_client.reclamationclient', verbose_name='Réclamation Client'),
        ),
        migrations.AlterField(
            model_name='actioncorrective',
            name='cause_racine',
            field=models.TextField(blank=True, verbose_name='Cause racine'),
        ),
        migrations.AlterField(
            model_name='actioncorrective',
            name='lap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accident_travail.lap8jours', verbose_name='LAP 8 jours'),
        ),
    ]
