# Generated by Django 4.2.30 on 2026-09-03 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_section_responsable_n1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Généré automatiquement : PDP + AAMMM + séquence (ex : PDP2609001)', max_length=30, unique=True, verbose_name='Référence PDP')),
                ('type_operation', models.CharField(choices=[('ponctuelle', 'Ponctuelle'), ('annuelle', 'Annuelle')], default='ponctuelle', max_length=20, verbose_name="Nature de l'opération (Type)")),
                ('nature_operation', models.CharField(default='Retouche techniques sur Longerons', max_length=255, verbose_name="Intitulé de l'opération")),
                ('eu_nom', models.CharField(max_length=200, verbose_name='E.U. - Nom')),
                ('eu_adresse', models.TextField(blank=True, verbose_name='E.U. - Adresse')),
                ('eu_telephone', models.CharField(blank=True, max_length=50, verbose_name='E.U. - Téléphone')),
                ('eu_representant_nom', models.CharField(blank=True, max_length=150, verbose_name='E.U. - Représentant (M.)')),
                ('eu_representant_fonction', models.CharField(blank=True, max_length=150, verbose_name='E.U. - Fonction')),
                ('eu_representant_telephone', models.CharField(blank=True, max_length=50, verbose_name='E.U. - Représentant Tél.')),
                ('ee_nom', models.CharField(default='AB Serve', max_length=200, verbose_name='E.E. - Nom')),
                ('ee_adresse', models.TextField(blank=True, verbose_name='E.E. - Adresse')),
                ('ee_telephone', models.CharField(blank=True, max_length=50, verbose_name='E.E. - Téléphone')),
                ('ee_representant_nom', models.CharField(blank=True, max_length=150, verbose_name='E.E. - Représentant (M.)')),
                ('ee_representant_fonction', models.CharField(blank=True, max_length=150, verbose_name='E.E. - Fonction')),
                ('ee_representant_telephone', models.CharField(blank=True, max_length=50, verbose_name='E.E. - Représentant Tél.')),
                ('lieu_intervention', models.CharField(blank=True, max_length=255, verbose_name="Lieu de l'intervention")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date prévue de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date prévue de fin')),
                ('horaire_travail', models.CharField(blank=True, max_length=150, verbose_name='Horaire de travail prévu')),
                ('effectif_prevu', models.CharField(blank=True, max_length=100, verbose_name='Effectif E.E. prévu sur le site')),
                ('duree_approximative', models.CharField(blank=True, max_length=100, verbose_name="Durée approximative de l'opération")),
                ('sous_traitants', models.TextField(blank=True, verbose_name='Sous-traitants éventuels')),
                ('date_visite_prealable', models.DateField(blank=True, null=True, verbose_name='Date de la visite préalable')),
                ('secteur_intervention', models.CharField(blank=True, max_length=255, verbose_name="Secteur d'intervention")),
                ('itineraire', models.TextField(default='Selon plan de circulation en vigueur au sein du site de Renault', verbose_name='Itinéraire à suivre')),
                ('zone_danger_particulier', models.TextField(blank=True, verbose_name='Zone présentant un danger particulier')),
                ('locaux_mis_disposition', models.TextField(blank=True, verbose_name="Locaux (bureaux, vestiaires, sanitaires, réfectoires) mis à disposition de l'E.E.")),
                ('appareils_mis_disposition', models.TextField(default='N/A (hormis matériels informatiques)', verbose_name="Appareils mis à disposition par l'E.U. à l'E.E.")),
                ('numeros_urgence', models.TextField(default='SAMU : 15 | Sapeurs Pompiers : 18 | Gendarmerie : 17 | Tél. portable : 112', verbose_name="Numéros d'urgence du site")),
                ('infirmerie_trousse_sst_location', models.TextField(blank=True, verbose_name="Emplacement de l'infirmerie, trousse de secours, liste des SST")),
                ('consigne_evacuation', models.TextField(blank=True, verbose_name="Consigne en cas d'évacuation générale")),
                ('suivi_medical_renforce', models.BooleanField(default=False, verbose_name="Postes relevant d'un Suivi Individuel Renforcé (SIR) ?")),
                ('postes_concernes', models.TextField(blank=True, verbose_name='Postes concernés (+ copie Médecine du Travail)')),
                ('remarques_cssct', models.TextField(blank=True, verbose_name="Remarques et avis du CSSCT de l'E.E. si nécessaire")),
                ('date_signature_eu', models.DateField(blank=True, null=True, verbose_name='Date signature E.U.')),
                ('signature_eu_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom signataire E.U.')),
                ('signature_eu_image', models.TextField(blank=True, verbose_name='Signature E.U. (Base64)')),
                ('date_signature_ee', models.DateField(blank=True, null=True, verbose_name='Date signature E.E.')),
                ('signature_ee_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom signataire E.E.')),
                ('signature_ee_image', models.TextField(blank=True, verbose_name='Signature E.E. (Base64)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé / En cours'), ('cloture', 'Clôturé / Archivé')], default='brouillon', max_length=20, verbose_name='Statut du document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_prevention_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_prevention', to='accounts.customer', verbose_name='Client E.U. (Sage)')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_prevention', to='accounts.section', verbose_name='Section')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_prevention', to='accounts.site', verbose_name='Site concerné')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_prevention', to='accounts.societe', verbose_name='Société (E.E.)')),
            ],
            options={
                'verbose_name': 'Plan de Prévention Simplifié',
                'verbose_name_plural': 'Plans de Prévention Simplifiés',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanPreventionRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_risque', models.CharField(max_length=50, verbose_name='Code du risque')),
                ('libelle_risque', models.TextField(verbose_name='Domaine et nature du risque')),
                ('concerne_eu', models.BooleanField(default=False, verbose_name='Risque / Interférence E.U.')),
                ('concerne_ee', models.BooleanField(default=False, verbose_name='Risque E.E.')),
                ('mesures_prevention', models.TextField(blank=True, verbose_name='Mesures de prévention retenues')),
                ('mise_en_oeuvre_eu', models.BooleanField(default=False, verbose_name='Mise en œuvre E.U.')),
                ('mise_en_oeuvre_ee', models.BooleanField(default=False, verbose_name='Mise en œuvre E.E.')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('pdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='plan_prevention.planprevention', verbose_name='Plan de prévention')),
            ],
            options={
                'verbose_name': 'Risque PDP',
                'verbose_name_plural': 'Risques PDP',
                'ordering': ('ordre', 'pk'),
            },
        ),
    ]
