# Generated by Django 4.2.30 on 2026-09-03 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_existing_pdp_risques(apps, schema_editor):
    Processus = apps.get_model('gestion_documentaire', 'Processus')
    Risque = apps.get_model('plan_prevention', 'Risque')
    PlanPreventionRisque = apps.get_model('plan_prevention', 'PlanPreventionRisque')

    proc = Processus.objects.filter(code="PM01").first() or Processus.objects.filter(is_active=True).first()
    if not proc:
        proc = Processus.objects.create(
            code="PM01",
            nom="Pilotage et amélioration du SMQS",
            is_active=True,
        )

    for r_pdp in PlanPreventionRisque.objects.all():
        code = getattr(r_pdp, 'code_risque', 'def') or 'def'
        libelle = getattr(r_pdp, 'libelle_risque', '') or f"Risque PDP #{r_pdp.pk}"
        
        r_obj, _ = Risque.objects.get_or_create(
            identification=libelle,
            defaults={
                "processus": proc,
                "activite": f"Prévention PDP ({code})",
                "probabilite": 1,
                "gravite": 1,
                "moyen_maitrise_valeur": "1",
                "is_active": True,
            }
        )
        r_pdp.risque = r_obj
        r_pdp.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_documentaire', '0001_initial'),
        ('plan_prevention', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(max_length=255, verbose_name='Activité / Environnement')),
                ('identification', models.TextField(verbose_name='Identification du risque')),
                ('probabilite', models.IntegerField(choices=[(1, '1 – Peu probable'), (2, '2 – Probable'), (3, '3 – Attendu')], verbose_name='P – Probabilité')),
                ('gravite', models.IntegerField(choices=[(1, '1 – Mineur'), (2, '2 – Significatif'), (3, '3 – Grave')], verbose_name='G – Gravité')),
                ('risque', models.FloatField(default=0, editable=False, verbose_name='R (P×G)')),
                ('moyens_maitrise', models.TextField(blank=True, verbose_name='Moyens de maîtrise existants')),
                ('moyen_maitrise_valeur', models.CharField(choices=[('1', '1 – Actions préventives inexistantes ou inefficaces'), ('0.5', '0,5 – Actions en place, barrière partielle'), ('0.1', '0,1 – Barrière forte, personnel exemplaire')], default='1', max_length=4, verbose_name='M – Moyen de maîtrise')),
                ('risque_residuel', models.FloatField(default=0, editable=False, verbose_name='RR (R×M)')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmé / Conforme')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_risques', to=settings.AUTH_USER_MODEL)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='gestion_documentaire.processus', verbose_name='Processus')),
            ],
            options={
                'verbose_name': 'Risque',
                'verbose_name_plural': 'Risques',
                'ordering': ['-risque_residuel', 'processus', 'activite'],
            },
        ),
        migrations.AddField(
            model_name='planpreventionrisque',
            name='risque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdp_associations', to='plan_prevention.risque', verbose_name='Risque'),
        ),
        migrations.RunPython(migrate_existing_pdp_risques, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='planpreventionrisque',
            name='risque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdp_associations', to='plan_prevention.risque', verbose_name='Risque'),
        ),
        migrations.RemoveField(
            model_name='planpreventionrisque',
            name='code_risque',
        ),
        migrations.RemoveField(
            model_name='planpreventionrisque',
            name='libelle_risque',
        ),
    ]
