# Generated by Django 4.2.30 on 2026-09-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_prevention', '0002_pdp_risque_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprevention',
            name='appareils_mis_disposition',
            field=models.TextField(blank=True, default='', verbose_name="Appareils mis à disposition par l'E.U. à l'E.E."),
        ),
        migrations.AlterField(
            model_name='planprevention',
            name='ee_nom',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='E.E. - Nom'),
        ),
        migrations.AlterField(
            model_name='planprevention',
            name='eu_nom',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='E.U. - Nom'),
        ),
        migrations.AlterField(
            model_name='planprevention',
            name='itineraire',
            field=models.TextField(blank=True, default='', verbose_name='Itinéraire à suivre'),
        ),
        migrations.AlterField(
            model_name='planprevention',
            name='nature_operation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Intitulé de l'opération"),
        ),
        migrations.AlterField(
            model_name='planprevention',
            name='numeros_urgence',
            field=models.TextField(blank=True, default='', verbose_name="Numéros d'urgence du site"),
        ),
        migrations.AlterField(
            model_name='planpreventionrisque',
            name='pdp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdp_risques', to='plan_prevention.planprevention', verbose_name='Plan de prévention'),
        ),
    ]
