# Generated by Django 4.2.30 on 2026-09-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_prevention', '0004_pdp_risquepdp_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Risque',
        ),
    ]
